var collectionsData = [
    {
        'title' : 'Anime',
        'new'   : true,
        'icon'  : 'files/blisters/anime/preview/01.png',
        'list'  : [
            ['files/blisters/anime/preview/01.png', 'files/blisters/anime/01.png'],
            ['files/blisters/anime/preview/02.png', 'files/blisters/anime/02.png'],
            ['files/blisters/anime/preview/03.png', 'files/blisters/anime/03.png'],
            ['files/blisters/anime/preview/04.png', 'files/blisters/anime/04.png'],
            ['files/blisters/anime/preview/05.png', 'files/blisters/anime/05.png'],
            ['files/blisters/anime/preview/06.png', 'files/blisters/anime/06.png'],
            ['files/blisters/anime/preview/07.png', 'files/blisters/anime/07.png'],
            ['files/blisters/anime/preview/08.png', 'files/blisters/anime/08.png'],
            ['files/blisters/anime/preview/09.png', 'files/blisters/anime/09.png'],
            ['files/blisters/anime/preview/10.png', 'files/blisters/anime/10.png'],
            ['files/blisters/anime/preview/11.png', 'files/blisters/anime/11.png'],
            ['files/blisters/anime/preview/12.png', 'files/blisters/anime/12.png'],
            ['files/blisters/anime/preview/13.png', 'files/blisters/anime/13.png'],
            ['files/blisters/anime/preview/14.png', 'files/blisters/anime/14.png'],
            ['files/blisters/anime/preview/15.png', 'files/blisters/anime/15.png'],
            ['files/blisters/anime/preview/16.png', 'files/blisters/anime/16.png'],
            ['files/blisters/anime/preview/17.png', 'files/blisters/anime/17.png'],
            ['files/blisters/anime/preview/18.png', 'files/blisters/anime/18.png']
        ]
    },
    {
        'title' : 'Arthouse',
        'icon'  : 'files/blisters/arthouse/preview/01.png',
        'list'  : [
            ['files/blisters/arthouse/preview/01.png', 'files/blisters/arthouse/01.png'],
            ['files/blisters/arthouse/preview/02.png', 'files/blisters/arthouse/02.png'],
            ['files/blisters/arthouse/preview/03.png', 'files/blisters/arthouse/03.png'],
            ['files/blisters/arthouse/preview/04.png', 'files/blisters/arthouse/04.png'],
            ['files/blisters/arthouse/preview/05.png', 'files/blisters/arthouse/05.png'],
            ['files/blisters/arthouse/preview/06.png', 'files/blisters/arthouse/06.png'],
            ['files/blisters/arthouse/preview/07.png', 'files/blisters/arthouse/07.png'],
            ['files/blisters/arthouse/preview/08.png', 'files/blisters/arthouse/08.png'],
            ['files/blisters/arthouse/preview/09.png', 'files/blisters/arthouse/09.png'],
            ['files/blisters/arthouse/preview/10.png', 'files/blisters/arthouse/10.png'],
            ['files/blisters/arthouse/preview/11.png', 'files/blisters/arthouse/11.png'],
            ['files/blisters/arthouse/preview/12.png', 'files/blisters/arthouse/12.png'],
            ['files/blisters/arthouse/preview/13.png', 'files/blisters/arthouse/13.png'],
            ['files/blisters/arthouse/preview/14.png', 'files/blisters/arthouse/14.png'],
            ['files/blisters/arthouse/preview/15.png', 'files/blisters/arthouse/15.png'],
            ['files/blisters/arthouse/preview/16.png', 'files/blisters/arthouse/16.png'],
            ['files/blisters/arthouse/preview/17.png', 'files/blisters/arthouse/17.png'],
            ['files/blisters/arthouse/preview/18.png', 'files/blisters/arthouse/18.png'],
            ['files/blisters/arthouse/preview/19.png', 'files/blisters/arthouse/19.png'],
            ['files/blisters/arthouse/preview/20.png', 'files/blisters/arthouse/20.png'],
            ['files/blisters/arthouse/preview/21.png', 'files/blisters/arthouse/21.png'],
            ['files/blisters/arthouse/preview/22.png', 'files/blisters/arthouse/22.png'],
            ['files/blisters/arthouse/preview/23.png', 'files/blisters/arthouse/23.png'],
            ['files/blisters/arthouse/preview/24.png', 'files/blisters/arthouse/24.png'],
            ['files/blisters/arthouse/preview/25.png', 'files/blisters/arthouse/25.png'],
            ['files/blisters/arthouse/preview/26.png', 'files/blisters/arthouse/26.png'],
            ['files/blisters/arthouse/preview/27.png', 'files/blisters/arthouse/27.png'],
            ['files/blisters/arthouse/preview/28.png', 'files/blisters/arthouse/28.png'],
            ['files/blisters/arthouse/preview/29.png', 'files/blisters/arthouse/29.png'],
            ['files/blisters/arthouse/preview/30.png', 'files/blisters/arthouse/30.png'],
            ['files/blisters/arthouse/preview/31.png', 'files/blisters/arthouse/31.png'],
            ['files/blisters/arthouse/preview/32.png', 'files/blisters/arthouse/32.png'],
            ['files/blisters/arthouse/preview/33.png', 'files/blisters/arthouse/33.png'],
            ['files/blisters/arthouse/preview/34.png', 'files/blisters/arthouse/34.png'],
            ['files/blisters/arthouse/preview/35.png', 'files/blisters/arthouse/35.png'],
            ['files/blisters/arthouse/preview/36.png', 'files/blisters/arthouse/36.png']
        ]
    },
    {
        'title' : 'British Edition Mixed',
        'icon'  : 'files/blisters/british-edition-mixed/preview/01.png',
        'list'  : [
            ['files/blisters/british-edition-mixed/preview/01.png', 'files/blisters/british-edition-mixed/01.png'],
            ['files/blisters/british-edition-mixed/preview/02.png', 'files/blisters/british-edition-mixed/02.png'],
            ['files/blisters/british-edition-mixed/preview/03.png', 'files/blisters/british-edition-mixed/03.png'],
            ['files/blisters/british-edition-mixed/preview/04.png', 'files/blisters/british-edition-mixed/04.png'],
            ['files/blisters/british-edition-mixed/preview/05.png', 'files/blisters/british-edition-mixed/05.png'],
            ['files/blisters/british-edition-mixed/preview/06.png', 'files/blisters/british-edition-mixed/06.png'],
            ['files/blisters/british-edition-mixed/preview/07.png', 'files/blisters/british-edition-mixed/07.png'],
            ['files/blisters/british-edition-mixed/preview/08.png', 'files/blisters/british-edition-mixed/08.png'],
            ['files/blisters/british-edition-mixed/preview/09.png', 'files/blisters/british-edition-mixed/09.png'],
            ['files/blisters/british-edition-mixed/preview/10.png', 'files/blisters/british-edition-mixed/10.png'],
            ['files/blisters/british-edition-mixed/preview/11.png', 'files/blisters/british-edition-mixed/11.png'],
            ['files/blisters/british-edition-mixed/preview/12.png', 'files/blisters/british-edition-mixed/12.png'],
            ['files/blisters/british-edition-mixed/preview/13.png', 'files/blisters/british-edition-mixed/13.png'],
            ['files/blisters/british-edition-mixed/preview/14.png', 'files/blisters/british-edition-mixed/14.png'],
            ['files/blisters/british-edition-mixed/preview/15.png', 'files/blisters/british-edition-mixed/15.png'],
            ['files/blisters/british-edition-mixed/preview/16.png', 'files/blisters/british-edition-mixed/16.png'],
            ['files/blisters/british-edition-mixed/preview/17.png', 'files/blisters/british-edition-mixed/17.png'],
            ['files/blisters/british-edition-mixed/preview/18.png', 'files/blisters/british-edition-mixed/18.png'],
            ['files/blisters/british-edition-mixed/preview/19.png', 'files/blisters/british-edition-mixed/19.png'],
            ['files/blisters/british-edition-mixed/preview/20.png', 'files/blisters/british-edition-mixed/20.png'],
            ['files/blisters/british-edition-mixed/preview/21.png', 'files/blisters/british-edition-mixed/21.png'],
            ['files/blisters/british-edition-mixed/preview/22.png', 'files/blisters/british-edition-mixed/22.png'],
            ['files/blisters/british-edition-mixed/preview/23.png', 'files/blisters/british-edition-mixed/23.png'],
            ['files/blisters/british-edition-mixed/preview/24.png', 'files/blisters/british-edition-mixed/24.png'],
            ['files/blisters/british-edition-mixed/preview/25.png', 'files/blisters/british-edition-mixed/25.png'],
            ['files/blisters/british-edition-mixed/preview/26.png', 'files/blisters/british-edition-mixed/26.png'],
            ['files/blisters/british-edition-mixed/preview/27.png', 'files/blisters/british-edition-mixed/27.png'],
            ['files/blisters/british-edition-mixed/preview/28.png', 'files/blisters/british-edition-mixed/28.png'],
            ['files/blisters/british-edition-mixed/preview/29.png', 'files/blisters/british-edition-mixed/29.png'],
            ['files/blisters/british-edition-mixed/preview/30.png', 'files/blisters/british-edition-mixed/30.png'],
            ['files/blisters/british-edition-mixed/preview/31.png', 'files/blisters/british-edition-mixed/31.png'],
            ['files/blisters/british-edition-mixed/preview/32.png', 'files/blisters/british-edition-mixed/32.png'],
            ['files/blisters/british-edition-mixed/preview/33.png', 'files/blisters/british-edition-mixed/33.png'],
            ['files/blisters/british-edition-mixed/preview/34.png', 'files/blisters/british-edition-mixed/34.png'],
            ['files/blisters/british-edition-mixed/preview/35.png', 'files/blisters/british-edition-mixed/35.png'],
            ['files/blisters/british-edition-mixed/preview/36.png', 'files/blisters/british-edition-mixed/36.png']
        ]
    },
    {
        'title' : 'British Edition Sport',
        'icon'  : 'files/blisters/british-edition-sport/preview/01.png',
        'list'  : [
            ['files/blisters/british-edition-sport/preview/01.png', 'files/blisters/british-edition-sport/01.png'],
            ['files/blisters/british-edition-sport/preview/02.png', 'files/blisters/british-edition-sport/02.png'],
            ['files/blisters/british-edition-sport/preview/03.png', 'files/blisters/british-edition-sport/03.png'],
            ['files/blisters/british-edition-sport/preview/04.png', 'files/blisters/british-edition-sport/04.png'],
            ['files/blisters/british-edition-sport/preview/05.png', 'files/blisters/british-edition-sport/05.png'],
            ['files/blisters/british-edition-sport/preview/06.png', 'files/blisters/british-edition-sport/06.png'],
            ['files/blisters/british-edition-sport/preview/07.png', 'files/blisters/british-edition-sport/07.png'],
            ['files/blisters/british-edition-sport/preview/08.png', 'files/blisters/british-edition-sport/08.png'],
            ['files/blisters/british-edition-sport/preview/09.png', 'files/blisters/british-edition-sport/09.png'],
            ['files/blisters/british-edition-sport/preview/10.png', 'files/blisters/british-edition-sport/10.png'],
            ['files/blisters/british-edition-sport/preview/11.png', 'files/blisters/british-edition-sport/11.png'],
            ['files/blisters/british-edition-sport/preview/12.png', 'files/blisters/british-edition-sport/12.png'],
            ['files/blisters/british-edition-sport/preview/13.png', 'files/blisters/british-edition-sport/13.png'],
            ['files/blisters/british-edition-sport/preview/14.png', 'files/blisters/british-edition-sport/14.png'],
            ['files/blisters/british-edition-sport/preview/15.png', 'files/blisters/british-edition-sport/15.png'],
            ['files/blisters/british-edition-sport/preview/16.png', 'files/blisters/british-edition-sport/16.png'],
            ['files/blisters/british-edition-sport/preview/17.png', 'files/blisters/british-edition-sport/17.png'],
            ['files/blisters/british-edition-sport/preview/18.png', 'files/blisters/british-edition-sport/18.png'],
            ['files/blisters/british-edition-sport/preview/19.png', 'files/blisters/british-edition-sport/19.png'],
            ['files/blisters/british-edition-sport/preview/20.png', 'files/blisters/british-edition-sport/20.png'],
            ['files/blisters/british-edition-sport/preview/21.png', 'files/blisters/british-edition-sport/21.png'],
            ['files/blisters/british-edition-sport/preview/22.png', 'files/blisters/british-edition-sport/22.png'],
            ['files/blisters/british-edition-sport/preview/23.png', 'files/blisters/british-edition-sport/23.png'],
            ['files/blisters/british-edition-sport/preview/24.png', 'files/blisters/british-edition-sport/24.png'],
            ['files/blisters/british-edition-sport/preview/25.png', 'files/blisters/british-edition-sport/25.png'],
            ['files/blisters/british-edition-sport/preview/26.png', 'files/blisters/british-edition-sport/26.png'],
            ['files/blisters/british-edition-sport/preview/27.png', 'files/blisters/british-edition-sport/27.png'],
            ['files/blisters/british-edition-sport/preview/28.png', 'files/blisters/british-edition-sport/28.png'],
            ['files/blisters/british-edition-sport/preview/29.png', 'files/blisters/british-edition-sport/29.png'],
            ['files/blisters/british-edition-sport/preview/30.png', 'files/blisters/british-edition-sport/30.png'],
            ['files/blisters/british-edition-sport/preview/31.png', 'files/blisters/british-edition-sport/31.png'],
            ['files/blisters/british-edition-sport/preview/32.png', 'files/blisters/british-edition-sport/32.png'],
            ['files/blisters/british-edition-sport/preview/33.png', 'files/blisters/british-edition-sport/33.png'],
            ['files/blisters/british-edition-sport/preview/34.png', 'files/blisters/british-edition-sport/34.png'],
            ['files/blisters/british-edition-sport/preview/35.png', 'files/blisters/british-edition-sport/35.png'],
            ['files/blisters/british-edition-sport/preview/36.png', 'files/blisters/british-edition-sport/36.png']
        ]
    },
    {
        'title' : 'I\'m sorry mom',
        'icon'  : 'files/blisters/i-am-sorry-mom/preview/01.png',
        'list'  : [
            ['files/blisters/i-am-sorry-mom/preview/01.png', 'files/blisters/i-am-sorry-mom/01.png'],
            ['files/blisters/i-am-sorry-mom/preview/02.png', 'files/blisters/i-am-sorry-mom/02.png'],
            ['files/blisters/i-am-sorry-mom/preview/03.png', 'files/blisters/i-am-sorry-mom/03.png'],
            ['files/blisters/i-am-sorry-mom/preview/04.png', 'files/blisters/i-am-sorry-mom/04.png'],
            ['files/blisters/i-am-sorry-mom/preview/05.png', 'files/blisters/i-am-sorry-mom/05.png'],
            ['files/blisters/i-am-sorry-mom/preview/06.png', 'files/blisters/i-am-sorry-mom/06.png'],
            ['files/blisters/i-am-sorry-mom/preview/07.png', 'files/blisters/i-am-sorry-mom/07.png'],
            ['files/blisters/i-am-sorry-mom/preview/08.png', 'files/blisters/i-am-sorry-mom/08.png'],
            ['files/blisters/i-am-sorry-mom/preview/09.png', 'files/blisters/i-am-sorry-mom/09.png'],
            ['files/blisters/i-am-sorry-mom/preview/10.png', 'files/blisters/i-am-sorry-mom/10.png'],
            ['files/blisters/i-am-sorry-mom/preview/11.png', 'files/blisters/i-am-sorry-mom/11.png'],
            ['files/blisters/i-am-sorry-mom/preview/12.png', 'files/blisters/i-am-sorry-mom/12.png'],
            ['files/blisters/i-am-sorry-mom/preview/13.png', 'files/blisters/i-am-sorry-mom/13.png'],
            ['files/blisters/i-am-sorry-mom/preview/14.png', 'files/blisters/i-am-sorry-mom/14.png'],
            ['files/blisters/i-am-sorry-mom/preview/15.png', 'files/blisters/i-am-sorry-mom/15.png'],
            ['files/blisters/i-am-sorry-mom/preview/16.png', 'files/blisters/i-am-sorry-mom/16.png'],
            ['files/blisters/i-am-sorry-mom/preview/17.png', 'files/blisters/i-am-sorry-mom/17.png'],
            ['files/blisters/i-am-sorry-mom/preview/18.png', 'files/blisters/i-am-sorry-mom/18.png'],
            ['files/blisters/i-am-sorry-mom/preview/19.png', 'files/blisters/i-am-sorry-mom/19.png'],
            ['files/blisters/i-am-sorry-mom/preview/20.png', 'files/blisters/i-am-sorry-mom/20.png'],
            ['files/blisters/i-am-sorry-mom/preview/21.png', 'files/blisters/i-am-sorry-mom/21.png'],
            ['files/blisters/i-am-sorry-mom/preview/22.png', 'files/blisters/i-am-sorry-mom/22.png'],
            ['files/blisters/i-am-sorry-mom/preview/23.png', 'files/blisters/i-am-sorry-mom/23.png'],
            ['files/blisters/i-am-sorry-mom/preview/24.png', 'files/blisters/i-am-sorry-mom/24.png'],
            ['files/blisters/i-am-sorry-mom/preview/25.png', 'files/blisters/i-am-sorry-mom/25.png'],
            ['files/blisters/i-am-sorry-mom/preview/26.png', 'files/blisters/i-am-sorry-mom/26.png'],
            ['files/blisters/i-am-sorry-mom/preview/27.png', 'files/blisters/i-am-sorry-mom/27.png'],
            ['files/blisters/i-am-sorry-mom/preview/28.png', 'files/blisters/i-am-sorry-mom/28.png'],
            ['files/blisters/i-am-sorry-mom/preview/29.png', 'files/blisters/i-am-sorry-mom/29.png'],
            ['files/blisters/i-am-sorry-mom/preview/30.png', 'files/blisters/i-am-sorry-mom/30.png'],
            ['files/blisters/i-am-sorry-mom/preview/31.png', 'files/blisters/i-am-sorry-mom/31.png'],
            ['files/blisters/i-am-sorry-mom/preview/32.png', 'files/blisters/i-am-sorry-mom/32.png'],
            ['files/blisters/i-am-sorry-mom/preview/33.png', 'files/blisters/i-am-sorry-mom/33.png'],
            ['files/blisters/i-am-sorry-mom/preview/34.png', 'files/blisters/i-am-sorry-mom/34.png'],
            ['files/blisters/i-am-sorry-mom/preview/35.png', 'files/blisters/i-am-sorry-mom/35.png'],
            ['files/blisters/i-am-sorry-mom/preview/36.png', 'files/blisters/i-am-sorry-mom/36.png']
        ]
    },
    {
        'title' : 'Pin-up',
        'new'   : true,
        'icon'  : 'files/blisters/pin-up/preview/01.png',
        'list'  : [
            ['files/blisters/pin-up/preview/01.png', 'files/blisters/pin-up/01.png'],
            ['files/blisters/pin-up/preview/02.png', 'files/blisters/pin-up/02.png'],
            ['files/blisters/pin-up/preview/03.png', 'files/blisters/pin-up/03.png'],
            ['files/blisters/pin-up/preview/04.png', 'files/blisters/pin-up/04.png'],
            ['files/blisters/pin-up/preview/05.png', 'files/blisters/pin-up/05.png'],
            ['files/blisters/pin-up/preview/06.png', 'files/blisters/pin-up/06.png'],
            ['files/blisters/pin-up/preview/07.png', 'files/blisters/pin-up/07.png'],
            ['files/blisters/pin-up/preview/08.png', 'files/blisters/pin-up/08.png'],
            ['files/blisters/pin-up/preview/09.png', 'files/blisters/pin-up/09.png'],
            ['files/blisters/pin-up/preview/10.png', 'files/blisters/pin-up/10.png'],
            ['files/blisters/pin-up/preview/11.png', 'files/blisters/pin-up/11.png'],
            ['files/blisters/pin-up/preview/12.png', 'files/blisters/pin-up/12.png'],
            ['files/blisters/pin-up/preview/13.png', 'files/blisters/pin-up/13.png'],
            ['files/blisters/pin-up/preview/14.png', 'files/blisters/pin-up/14.png'],
            ['files/blisters/pin-up/preview/15.png', 'files/blisters/pin-up/15.png'],
            ['files/blisters/pin-up/preview/16.png', 'files/blisters/pin-up/16.png'],
            ['files/blisters/pin-up/preview/17.png', 'files/blisters/pin-up/17.png'],
            ['files/blisters/pin-up/preview/18.png', 'files/blisters/pin-up/18.png'],
            ['files/blisters/pin-up/preview/19.png', 'files/blisters/pin-up/19.png'],
            ['files/blisters/pin-up/preview/20.png', 'files/blisters/pin-up/20.png'],
            ['files/blisters/pin-up/preview/21.png', 'files/blisters/pin-up/21.png'],
            ['files/blisters/pin-up/preview/22.png', 'files/blisters/pin-up/22.png'],
            ['files/blisters/pin-up/preview/23.png', 'files/blisters/pin-up/23.png'],
            ['files/blisters/pin-up/preview/24.png', 'files/blisters/pin-up/24.png'],
            ['files/blisters/pin-up/preview/25.png', 'files/blisters/pin-up/25.png'],
            ['files/blisters/pin-up/preview/26.png', 'files/blisters/pin-up/26.png'],
            ['files/blisters/pin-up/preview/27.png', 'files/blisters/pin-up/27.png'],
            ['files/blisters/pin-up/preview/28.png', 'files/blisters/pin-up/28.png'],
            ['files/blisters/pin-up/preview/29.png', 'files/blisters/pin-up/29.png'],
            ['files/blisters/pin-up/preview/30.png', 'files/blisters/pin-up/30.png'],
            ['files/blisters/pin-up/preview/31.png', 'files/blisters/pin-up/31.png'],
            ['files/blisters/pin-up/preview/32.png', 'files/blisters/pin-up/32.png'],
            ['files/blisters/pin-up/preview/33.png', 'files/blisters/pin-up/33.png'],
            ['files/blisters/pin-up/preview/34.png', 'files/blisters/pin-up/34.png'],
            ['files/blisters/pin-up/preview/35.png', 'files/blisters/pin-up/35.png'],
            ['files/blisters/pin-up/preview/36.png', 'files/blisters/pin-up/36.png']
        ]
    },
    {
        'title' : 'Sexy Food',
        'icon'  : 'files/blisters/sexy-food/preview/01.png',
        'list'  : [
            ['files/blisters/sexy-food/preview/01.png', 'files/blisters/sexy-food/01.png'],
            ['files/blisters/sexy-food/preview/02.png', 'files/blisters/sexy-food/02.png'],
            ['files/blisters/sexy-food/preview/03.png', 'files/blisters/sexy-food/03.png'],
            ['files/blisters/sexy-food/preview/04.png', 'files/blisters/sexy-food/04.png'],
            ['files/blisters/sexy-food/preview/05.png', 'files/blisters/sexy-food/05.png'],
            ['files/blisters/sexy-food/preview/06.png', 'files/blisters/sexy-food/06.png'],
            ['files/blisters/sexy-food/preview/07.png', 'files/blisters/sexy-food/07.png'],
            ['files/blisters/sexy-food/preview/08.png', 'files/blisters/sexy-food/08.png'],
            ['files/blisters/sexy-food/preview/09.png', 'files/blisters/sexy-food/09.png'],
            ['files/blisters/sexy-food/preview/10.png', 'files/blisters/sexy-food/10.png'],
            ['files/blisters/sexy-food/preview/11.png', 'files/blisters/sexy-food/11.png'],
            ['files/blisters/sexy-food/preview/12.png', 'files/blisters/sexy-food/12.png']
        ]
    },
    {
        'title' : 'Technical',
        'icon'  : 'files/blisters/technical/preview/01.png',
        'list'  : [
            ['files/blisters/technical/preview/01.png', 'files/blisters/technical/01.png'],
            ['files/blisters/technical/preview/02.png', 'files/blisters/technical/02.png'],
            ['files/blisters/technical/preview/03.png', 'files/blisters/technical/03.png'],
            ['files/blisters/technical/preview/04.png', 'files/blisters/technical/04.png'],
            ['files/blisters/technical/preview/05.png', 'files/blisters/technical/05.png'],
            ['files/blisters/technical/preview/06.png', 'files/blisters/technical/06.png'],
            ['files/blisters/technical/preview/07.png', 'files/blisters/technical/07.png'],
            ['files/blisters/technical/preview/08.png', 'files/blisters/technical/08.png'],
            ['files/blisters/technical/preview/09.png', 'files/blisters/technical/09.png'],
            ['files/blisters/technical/preview/10.png', 'files/blisters/technical/10.png'],
            ['files/blisters/technical/preview/11.png', 'files/blisters/technical/11.png'],
            ['files/blisters/technical/preview/12.png', 'files/blisters/technical/12.png'],
            ['files/blisters/technical/preview/13.png', 'files/blisters/technical/13.png'],
            ['files/blisters/technical/preview/14.png', 'files/blisters/technical/14.png'],
            ['files/blisters/technical/preview/15.png', 'files/blisters/technical/15.png'],
            ['files/blisters/technical/preview/16.png', 'files/blisters/technical/16.png'],
            ['files/blisters/technical/preview/17.png', 'files/blisters/technical/17.png'],
            ['files/blisters/technical/preview/18.png', 'files/blisters/technical/18.png'],
            ['files/blisters/technical/preview/19.png', 'files/blisters/technical/19.png'],
            ['files/blisters/technical/preview/20.png', 'files/blisters/technical/20.png'],
            ['files/blisters/technical/preview/21.png', 'files/blisters/technical/21.png'],
            ['files/blisters/technical/preview/22.png', 'files/blisters/technical/22.png'],
            ['files/blisters/technical/preview/23.png', 'files/blisters/technical/23.png'],
            ['files/blisters/technical/preview/24.png', 'files/blisters/technical/24.png'],
            ['files/blisters/technical/preview/25.png', 'files/blisters/technical/25.png'],
            ['files/blisters/technical/preview/26.png', 'files/blisters/technical/26.png'],
            ['files/blisters/technical/preview/27.png', 'files/blisters/technical/27.png'],
            ['files/blisters/technical/preview/28.png', 'files/blisters/technical/28.png'],
            ['files/blisters/technical/preview/29.png', 'files/blisters/technical/29.png'],
            ['files/blisters/technical/preview/30.png', 'files/blisters/technical/30.png'],
            ['files/blisters/technical/preview/31.png', 'files/blisters/technical/31.png'],
            ['files/blisters/technical/preview/32.png', 'files/blisters/technical/32.png'],
            ['files/blisters/technical/preview/33.png', 'files/blisters/technical/33.png'],
            ['files/blisters/technical/preview/34.png', 'files/blisters/technical/34.png'],
            ['files/blisters/technical/preview/35.png', 'files/blisters/technical/35.png'],
            ['files/blisters/technical/preview/36.png', 'files/blisters/technical/36.png']
        ]
    },
    {
        'title' : 'Webcam',
        'new'   : true,
        'icon'  : 'files/blisters/webcam/preview/01.png',
        'list'  : [
            ['files/blisters/webcam/preview/01.png', 'files/blisters/webcam/01.png'],
            ['files/blisters/webcam/preview/02.png', 'files/blisters/webcam/02.png'],
            ['files/blisters/webcam/preview/03.png', 'files/blisters/webcam/03.png'],
            ['files/blisters/webcam/preview/04.png', 'files/blisters/webcam/04.png'],
            ['files/blisters/webcam/preview/05.png', 'files/blisters/webcam/05.png'],
            ['files/blisters/webcam/preview/06.png', 'files/blisters/webcam/06.png'],
            ['files/blisters/webcam/preview/07.png', 'files/blisters/webcam/07.png'],
            ['files/blisters/webcam/preview/08.png', 'files/blisters/webcam/08.png'],
            ['files/blisters/webcam/preview/09.png', 'files/blisters/webcam/09.png'],
            ['files/blisters/webcam/preview/10.png', 'files/blisters/webcam/10.png'],
            ['files/blisters/webcam/preview/11.png', 'files/blisters/webcam/11.png'],
            ['files/blisters/webcam/preview/12.png', 'files/blisters/webcam/12.png'],
            ['files/blisters/webcam/preview/13.png', 'files/blisters/webcam/13.png'],
            ['files/blisters/webcam/preview/14.png', 'files/blisters/webcam/14.png'],
            ['files/blisters/webcam/preview/15.png', 'files/blisters/webcam/15.png'],
            ['files/blisters/webcam/preview/16.png', 'files/blisters/webcam/16.png'],
            ['files/blisters/webcam/preview/17.png', 'files/blisters/webcam/17.png'],
            ['files/blisters/webcam/preview/18.png', 'files/blisters/webcam/18.png']
        ]
    }
];
